import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from 'components/main/Hero'
import About from 'components/card/About'
import Service from 'components/card/Service'
import Events from 'components/card/Events'
import Logo from 'components/main/Logo'
import Portfolio from 'components/card/Portfolio'
import Plans from 'components/main/Plans'
import Testimonial from 'components/main/Testimonial'
import Blog from 'components/main/Blog'
import Footer from 'components/shared/Footer'
import Header from 'components/shared/Header'
import AboutTeamCard from 'components/card/AboutTeamCard'
import Exprience from 'components/card/Exprience'
import MainAbout from 'components/main/MainAbout'
import MainEventCard from 'components/main/MainEventCard'
import MainService from 'components/main/MainService'
import MainPortfolio from 'components/main/MainPortfolio'
import Layout from 'components/layouts/Layout'
import BgImage3 from 'components/card/BgImage3'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Layout> */}
      <main className={styles.main}>
      {/* <div className="background-element"> */}
      <Header />
       <Hero />
       <AboutTeamCard />
       <MainAbout  />
       <Exprience />
       <MainService />
       <MainEventCard />
       <Logo />
       <MainPortfolio />
       <div className="">
          <BgImage3
            title="Let's Talk About Your Event Idea With Us"
            desc="Cras porttitor urna eu metus efficitur, a tempus ligula vehicula. Donec ornare pharetra metus nec vehicula. Etiam mauris dolor, interdum id vestibulum et pharetra ac libero. Etiam vestibulum in mi sit amet."
            buttonTitle="CONTACT US"
          />
        </div>
       <Testimonial />
       <Plans />
       <Blog />
       <Footer />
       {/* </div> */}
      </main>
      {/* </Layout> */}
    </>
  )
}
